# Generated by Django 5.2.1 on 2025-08-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_teams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='min_team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_team_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50, unique=True)),
                ('team_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.event')),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.team'),
        ),
    ]
