# Generated by Django 5.2.1 on 2025-08-20 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='student_sop',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student_phoneno',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number')]),
        ),
    ]
